pipeline {
	agent any
	stages {
		stage('Clean stage') {
			steps {
				dir("TransferFundsApp") {
					bat 'mvn clean'
				}
			}
		}
		stage('Compile stage') {
			steps {
				dir("TransferFundsApp") {
					bat 'mvn compile'
				}
			}
		}
		stage('Install stage') {
			steps {
				dir("TransferFundsApp") {
					bat 'mvn install'
				}
			}
		}
	}
}
